# -*- coding: utf-8 -*-
"""EmailSender

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OOlSVNf3rejmgsBgYymxc3rmr0oGRhVN
"""

pip install qrcode

import qrcode as qr 
img = qr.make("Hello World!")
img.save("Image.png")

img1 = qr.make("https://meetpasswordgenerator.netlify.app/")
img1.save("Image1.png")